[package]
name = "thetawave"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["serialize"] }
bevy_rapier2d = { version = "0.21.0", features = ["simd-stable"] }
bevy_egui = "0.20.2"
bevy_asset_loader = { version = "0.16.0", features = [
    "2d",
    "3d",
    "standard_dynamic_assets",
] }
serde = "1.0.159"
ron = "0.8.0"
rand = "0.8.5"
strum = "0.24.1"
strum_macros = "0.24.3"
console_error_panic_hook = "0.1.7"
bevy_kira_audio = { version = "0.15.0", features = ["mp3", "wav"] }
bevy_editor_pls = "0.4.0"
leafwing-input-manager = "0.9.1"

# bevy_framespace currently does not support wasm
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy_framepace = "0.12.1"

# optimize dev packages as we don't need them in debug version
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

# For bevy-rapier2d
[profile.release]
codegen-units = 1
