[package]
name = "theta-wave"
version = "0.1.7"
edition = "2021"

[dependencies]
bevy = "0.6.0"
bevy_rapier2d = {version = "0.12.0", features = ["simd-stable", "render"] }
serde = "1.0.127"
ron = "0.6.4"
rand = "0.8.4"
strum = "0.21.0"
strum_macros = "0.21"
